### PR TITLE
switch validation to gwt-bean-validators

### PR DESCRIPTION
**Pull request by ManfredTremmel**
fixed bug reported and got no answer the last three month for the
provided patch file:
https://github.com/ManfredTremmel/gwt-bean-validators/issues/1

### CODE REVIEW

**Comment by freddyboucher** [comment]
@ManfredTremmel 
Could you also update the README in your PR please:

from
`- [Bean Validation](http://www.gwtproject.org/doc/latest/DevGuideValidation.html)`
to
`- [gwt-bean-validators](https://github.com/ManfredTremmel/gwt-bean-validators)`

Thanks

**Comment by freddyboucher** [comment]
Ok so I tested it:
- in prod mode: all good
- in dev mode (run `mvn gwt:codeserver -pl gwt-storage-objectify-client -am`): it's broken with the following log:

> [INFO] --- gwt-maven-plugin:1.0-rc-9:codeserver (default-cli) @ gwt-storage-objectify ---
[INFO] Ignoring gwt-storage-objectify:gwt-storage-objectify-shared:jar:0.0.1-SNAPSHOT; neither a gwt-lib or jar:sources; Did you forget to use <type>gwt-lib</type> in the dependency declaration?
[INFO] Turning off precompile in incremental mode.
[INFO] Super Dev Mode starting up
[INFO]    workDir: /Users/freddyboucher/Private/Programming/gwt-storage-objectify/target/gwt/codeserver
[WARNING] ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[INFO]    Loading Java files in com.project.App.
[INFO]    Tracing compile failure path for type 'org.hibernate.validator.internal.constraintvalidators.bv.time.pastorpresent.PastOrPresentValidatorForInstant'
[INFO]       [ERROR] Errors in 'de/knightsoftnet/validators/supersource/org/hibernate/validator/internal/constraintvalidators/bv/time/pastorpresent/PastOrPresentValidatorForInstant.java'
[INFO]          [ERROR] Line 22: No source code is available for type javax.validation.constraints.PastOrPresent; did you forget to inherit a required module?
[INFO]       [ERROR] Errors in 'de/knightsoftnet/validators/client/constraints/AbstractNotGwtCompatibleValidator.java'
[INFO]          [ERROR] Line 38: No source code is available for type javax.validation.ConstraintValidatorContext; did you forget to inherit a required module?
[INFO]          [ERROR] Line 29: No source code is available for type javax.validation.ConstraintValidator<A,T>; did you forget to inherit a required module?
[INFO]    Tracing compile failure path for type 'com.google.gwt.validation.client.constraints.AbstractMaxValidator'
[INFO]       [ERROR] Errors in 'com/google/gwt/validation/client/constraints/AbstractMaxValidator.java'
[INFO]          [ERROR] Line 30: No source code is available for type javax.validation.constraints.Max; did you forget to inherit a required module?
[INFO]          [ERROR] Line 30: No source code is available for type javax.validation.ConstraintValidator<A,T>; did you forget to inherit a required module?


@ManfredTremmel 
Could you take a look please?

Thanks

**Comment by ManfredTremmel** [comment]
Hi @freddyboucher,
sorry, I've only tested on prod mode. I'll take a look on it

**Comment by ManfredTremmel** [comment]
looks like the provided scope caused the problems with the dev-mode compile

**Comment by freddyboucher** [comment]
Thanks @ManfredTremmel

**Pull request merged**
